version: '3.8'

services:
  couchdb:
    image: couchdb:3.1.1
    container_name: appia-couchdb
    volumes:
      - ./couchdb/data:/opt/couchdb/data
      - ./couchdb/config:/opt/couchdb/etc/local.d/
      - ./local.ini:/opt/couchdb/etc/local.ini
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
  appia:
    depends_on:
      - couchdb
    image: plethorachutney/appia:latest
    container_name: appia-web
    ports:
      - 8080:8080
    environment:
      - COUCHDB_USERNAME=${COUCHDB_USER}
      - COUCHDB_PASSWORD
      - COUCHDB_HOST=couchdb
